### PR TITLE
Update for BME688

### PR DESCRIPTION
**Pull request by caternuson**
For #42.

This at least allows getting a gas resistance value that varies with the BME688. There are a few key things that are *not* covered in the datasheet. Getting this working required looking through Bosch's driver here:
https://github.com/BoschSensortec/BME68x-Sensor-API

The BME680 is a "low" variant while the BME688 is a "high" variant. Key differences for the BME688/high variant:
* `run_gas` is actually bit 5 of `CTRL_GAS_1` (0x70) register. ([see here](https://github.com/BoschSensortec/BME68x-Sensor-API/blob/9f9b030c7236aa308252921973ec2abeb679c1bd/bme68x.c#L656))
* `gas_r_msb/lsb` are at 0x2C/0x2D, up two bytes from BME680. (this is in datasheet)
* gas resistance in ohms uses a different set of equations. ([see here](https://github.com/BoschSensortec/BME68x-Sensor-API/blob/9f9b030c7236aa308252921973ec2abeb679c1bd/bme68x.c#L961))

Tested with BME688 attached:
```python
Adafruit CircuitPython 6.3.0 on 2021-06-01; Adafruit ItsyBitsy M4 Express with samd51g19
>>> import bme680_simpletest

Temperature: 17.4 C
Gas: 1643 ohm
Humidity: 55.3 %
Pressure: 1010.344 hPa
Altitude = 24.23 meters

Temperature: 17.5 C
Gas: 1724 ohm
Humidity: 55.3 %
Pressure: 1010.350 hPa
Altitude = 24.17 meters
```

### CODE REVIEW

**Comment by tannewt** [comment]
Should we rename this bme68x to make it clear that it supports more than one SKU? Another option would be to make a separate 688 library that subclasses the 680 class. I like having separate libraries generally because it makes it very clear what is supported by any given driver.

**Comment by Technodad** [comment]
> I like having separate libraries generally because it makes it very clear what is supported by any given driver.

My 2¢ from the user side would be separate libraries. It’s clearer when coding, and probably saves a tiny bit of space when deployed.

**Comment by caternuson** [comment]
Just to be clear "separate library" = separate repo?

**Comment by ladyada** [comment]
separate repo is ok, but i think best to subclass rather than copy & paste it all over and make the small changes

**Comment by caternuson** [comment]
Agree. The code diff for this PR is essentially all that is specific to the BME688. The majority of the code is the same. How about renaming repo to BME68X and refactoring things into separate files for BME680 and BME688? Something like?
```
adafruit_bme68x\
    bme68x.py
    bme680.py
    bme688.py
```
Might be easier to keep code in one repo?

**Comment by tannewt** [comment]
> Just to be clear "separate library" = separate repo?

Yes, that is my preference generally.

> Might be easier to keep code in one repo?

 I think you are right that this is clearer as one repo. It'll be easier to grab all of the necessary files because they are all here. Switching to a package will be a breaking change though.

**Comment by caternuson** [comment]
What are the non-breaking options?

**Comment by tannewt** [comment]
The only one I can think of is creating a second repo with a 688 class that subclasses the 680 one.

**Comment by caternuson** [comment]
So I think we either break things or make the two repos and run into issues later trying to keep the code between them synced? Guess could make a new BMP688 repo be dependent on this (BMP680) repo? But seems like an odd way to setup things in terms of class inheritance.

Are there any objections to breaking things?

**Comment by Technodad** [comment]
Just tested this and confirm I'm getting lower (3-4Kohm) gas readings, and more importantly changing up and down.I did note that reading the gas every second produced a continuously increasing resistance reading; sleeping the loop for 10sec produced a much more stable value. A lot to learn about this sensor. 

Test environment was a Funhouse running v6.

**Comment by nickz9** [comment]
Thank you for the work on this! I did confirm it works just fine with the patch. Is there anything needed here for the merge? It would be nice to not require a manual patch.  I also like the rename to bme68x.

```
Before:
Temperature: 22.2 C
Gas (ohm), 12946860
Humidity: 25.6 %
Pressure: 842.155 hPa
Altitude = 1533.14 meters

Temperature: 22.2 C
Gas (ohm), 12946860
Humidity: 25.5 %
Pressure: 842.152 hPa
Altitude = 1533.16 meters

After:
Temperature: 22.2 C
Gas (ohm), 9026
Humidity: 25.8 %
Pressure: 842.161 hPa
Altitude = 1533.08 meters

Temperature: 22.2 C
Gas (ohm), 9017
Humidity: 25.8 %
Pressure: 842.163 hPa
Altitude = 1533.06 meters

**Comment by caternuson** [comment]
> Is there anything needed here for the merge? 

I think we're just waiting for decision on possible renaming and layout.

**Comment by somenice** [comment]
This update has resolved my issue with bme688 i2c gas readings as well. Thank you!

**Comment by caternuson** [comment]
Merging this as is. Can refactor later if desired and use conversation here as a starting point.

**Pull request merged**
