### PR TITLE
Add method to disable gas heater

### LINKED ISSUE #63: Method to disable heater please
To get a more reliable temperature reading, optionally disable heater for gas sensor (my use case is for `Adafruit_BME680_I2C`)

### PR DESCRIPTION
**Pull request by graeme-winter**
Setting either of temperature or heat time to zero will disable

Fixes adafruit/Adafruit_CircuitPython_BME680#63

### CODE REVIEW

**Comment by tekktrik** [comment]
Is this ready for review?

**Comment by graeme-winter** [comment]
I'll welcome some review comments, not had a chance to polish though

**Comment by caternuson** [comment]
I'd suggest using `None` to disable instead of `0`. That'd be similar to what is done in the Motor library for disabling servo outputs:
https://github.com/adafruit/Adafruit_CircuitPython_Motor/pull/27

**Review by FoamyGuy — APPROVED** [review]
I added a commit to tweak  this to use `None` instead of `0`.

The change looks good to me. 

Thank you @graeme-winter

**Pull request merged**
