### PR TITLE
Proposed patch items

### PR DESCRIPTION
**Pull request by tekktrik**
This is a running list of things that are candidates for library patches.  Using a pull request also lets me write out some things as well.  Draft so it doesn't get merged.

### CODE REVIEW

**Comment by tekktrik** [comment]
@kattni `min-similarity-lines` is now marked as to be changed to `12` in `.pylintrc`!

**Comment by kattni** [comment]
Excellent, @tekktrik, thank you!

**Comment by tekktrik** [comment]
Latest commit is the library patch for cookiecutter patch https://github.com/adafruit/cookiecutter-adafruit-circuitpython/commit/6675a7d766c425cbbf48e3a11262eb77025e5aaa (@kattni)

**Comment by tekktrik** [comment]
@kattni do we want to do the remaining patches from this soon?

**Comment by kattni** [comment]
@tekktrik Yes we do! Returning to this PR is on my list. If you could make sure it's up to date in the meantime, that would be great. I'm not sure if there are further patches needed, or if some of them were completed. Worth checking!

**Comment by tekktrik** [comment]
I believe I merged main into the branch so it should be up to date!

**Review by kattni — APPROVED** [review]
I would say don't bother with `setup.py` at this point, unless it will help your move to `pyproject.toml`. Otherwise, go ahead and apply the other changes please!

**Comment by tekktrik** [comment]
You got it!

**Comment by tekktrik** [comment]
`setup.py` conflict is easy to resolve, but trying to figure out how to handle that `sed` usage.  I think it should be patched, but asked in the dev channel before resolving that one.

**Comment by tekktrik** [comment]
Merge conflicts resolved.  Keeping the `python setup.py sdist` for the patch because only those 5 use `python -m build` so the other will catch on more libraries.

**Comment by tekktrik** [comment]
Actually, I just use a non-`pyproject.toml` library as the basis for the patch, should be good!

**Comment by tekktrik** [comment]
Actually these are also going to get changed due to the `pyproject.toml` transition, so it may be worth combining these changes at the same time.

**Comment by tekktrik** [comment]
Saved these remaining changes (plus a few additional things) in [this public gist](https://gist.github.com/tekktrik/1ad238ab755a5bf09b3fd47a57be2629) so we can revisit the remaining patches later.  Should be sufficient to just unify all the workflows across the libraries with these, which means it can/needs to be done at the same time as the `pyproject.toml` replacement since that will also change these files.

**Pull request closed without merging**
